import "@/app/globals.css";
import { inter } from "@/app/fonts/fonts";
import DashboardLayoutAccount from "@/app/components/usoMui/DashboardLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardLayoutAccount>
            {children}
        </DashboardLayoutAccount>
      </body>
    </html>
  );
}
