import localFont from "next/font/local";
import "./globals.css";
import { inter } from "./fonts/fonts";
import DashboardLayoutAccount from "./components/usoMui/DashboardLayout";

export const metadata = {
  title: "Destiny",
  description: "Generated by create Destiny",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardLayoutAccount>
          {children}
        </DashboardLayoutAccount>
      </body>
    </html>
  );
}
